### ISSUE TITLE
Update newer releases to Chef Supermarket

### ISSUE THREAD

**Issue by agperson** [mdsol/ice_cookbook#20]
Newest version is 0.2.13 but version on Supermarket is 0.2.8
https://supermarket.chef.io/cookbooks/ice

**Comment by rayrod2030** [comment]
Hi Daniel, If you want to use master or dev branch of a cookbook you can define the github project endpoint in your Beekshelf file until a release is made on the supermarket.

**Comment by agperson** [comment]
Thanks, I'm aware of that, but the latest release (from October 2013) never made it up there, and its confusing to not see expected behaviors.  It would be great to sync up the Supermarket entry with the repo and link to the repo from Supermarket as well!

**Comment by rayrod2030** [comment]
Hi Daniel I'll be working on this issue with the Medidata guys in the next few days based on their availability to push a new release to supermarket.

**Comment by ghost** [comment]
Closing this PR as lastest version was released to supermarket (0.2.14).
