### ISSUE TITLE
Suggest removing .ruby-gemset and .ruby-version files

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/ice_cookbook#24]
As more and more cookbook developers move to chefdk it doesn't really make much sense to have these files in the repo.  If a user wants to run their own artisanal hand-crafted set of gems they could do so using whatever method they prefer but I feel like this is a solved problem now with the introduction of chefdk.

**Comment by harryw** [comment]
I agree.

**Comment by rayrod2030** [comment]
Added as PR https://github.com/mdsol/ice_cookbook/pull/28
